name: Audio Pipeline

on:
  push:
    paths:
      - 'Dockerfile'
      - 'audio-processor.py'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading code from repo
        uses: actions/checkout@v6
      
      - name: Building Docker image
        run: docker build -t audio-processor .
      
      - name: Testing container
      - run: docker run --rm -v $(pwd)/tests:/data audio-processor /data/test.wav