name: Build and Test

on:
  push:
    paths-ignore:
      - 'README.md'
  
  

jobs:
  build-workflow:
    uses: ./.github/workflows/build-image.yaml
    with:
      push_to_ghcr: false
      image_tag: ${{ github.ref_name }}
 